import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Tandoori
  {
    id: 't1',
    name: 'Paneer Tikka',
    description: 'Fresh cottage cheese cubes marinated in yogurt and spices, grilled in a clay oven.',
    price: 240,
    category: 'Tandoori',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c175f0?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 't2',
    name: 'Tandoori Chicken',
    description: 'Whole chicken marinated in ginger-garlic paste and traditional spices, roasted to perfection.',
    price: 320,
    category: 'Tandoori',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 't3',
    name: 'Chicken Seekh Kebab',
    description: 'Minced chicken blended with herbs and spices, skewered and grilled.',
    price: 280,
    category: 'Tandoori',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 't4',
    name: 'Afghani Chicken',
    description: 'Chicken marinated in a creamy, mild spice blend, roasted until tender.',
    price: 360,
    category: 'Tandoori',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea8c5119c85?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 't5',
    name: 'Chicken Malai Tikka',
    description: 'Boneless chicken pieces marinated in cream, cheese, and mild spices, grilled to perfection.',
    price: 340,
    category: 'Tandoori',
    image: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 't6',
    name: 'Hara Bhara Kebab',
    description: 'Deep-fried spicy patties made with spinach, peas, and potatoes.',
    price: 210,
    category: 'Tandoori',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },

  // Main Course
  {
    id: 'm1',
    name: 'Dal Makhani',
    description: 'Black lentils slow-cooked overnight with creamy butter and tomatoes.',
    price: 220,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'm2',
    name: 'Butter Chicken',
    description: 'Tandoori chicken pieces cooked in a rich, buttery tomato gravy.',
    price: 350,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1603894584214-5d3161ca493e?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 'm3',
    name: 'Kadai Paneer',
    description: 'Paneer cubes cooked with bell peppers, onions, and ground spices.',
    price: 260,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'm4',
    name: 'Mutton Rogan Josh',
    description: 'Tender mutton pieces slow-cooked in a rich yogurt and onion gravy.',
    price: 450,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 'm5',
    name: 'Palak Paneer',
    description: 'Fresh spinach puree cooked with spices and cubes of cottage cheese.',
    price: 240,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1601050638911-30064f2666d6?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'm6',
    name: 'Chicken Tikka Masala',
    description: 'Roasted chunks of chicken tikka in a creamy, spicy tomato sauce.',
    price: 360,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
    isVegetarian: false,
  },
  {
    id: 'm7',
    name: 'Malai Kofta',
    description: 'Fried potato and paneer balls in a rich, creamy tomato and cashew-based gravy.',
    price: 280,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },

  // Breads
  {
    id: 'b1',
    name: 'Butter Naan',
    description: 'Soft leavened bread baked in tandoor and brushed with butter.',
    price: 45,
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'b2',
    name: 'Garlic Naan',
    description: 'Leavened bread topped with fresh garlic and coriander.',
    price: 55,
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1601050638917-3bf969fc4442?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'b3',
    name: 'Lacha Paratha',
    description: 'Multi-layered whole wheat bread baked in tandoor.',
    price: 50,
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1495147334217-fc133028bb37?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'b4',
    name: 'Missi Roti',
    description: 'Nutritious flatbread made with chickpea flour and wheat flour, seasoned with spices.',
    price: 40,
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'b5',
    name: 'Tandoori Roti',
    description: 'Traditional whole wheat flatbread baked in a clay oven.',
    price: 25,
    category: 'Breads',
    image: 'https://images.unsplash.com/photo-1495147334217-fc133028bb37?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },

  // Beverages
  {
    id: 'bv1',
    name: 'Masala Lassi',
    description: 'Refreshing yogurt-based drink with salt and spices.',
    price: 80,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1626788094620-30bb2692237a?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'bv2',
    name: 'Gulab Jamun (2pcs)',
    description: 'Soft milk balls fried and soaked in cardamom flavored sugar syrup.',
    price: 70,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1589112106431-1e913a7bd43b?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'bv3',
    name: 'Sweet Lassi',
    description: 'Classic Punjabi sweet yogurt drink, chilled and refreshing.',
    price: 90,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1626788094620-30bb2692237a?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'bv4',
    name: 'Fresh Lime Soda',
    description: 'Bubbly lime drink, available sweet or salted.',
    price: 60,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
  {
    id: 'bv5',
    name: 'Rasmalai (2pcs)',
    description: 'Soft paneer discs soaked in sweetened, thickened milk delicately flavored with cardamom.',
    price: 110,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?q=80&w=800&auto=format&fit=crop',
    isVegetarian: true,
  },
];
